services:
  nginx:
    volumes:
      - ./public:/app/public
  app:
    build:
      args:
        HOST_USER: ${HOST_USER}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    volumes:
      - .:/app
    tty: true