services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.Dockerfile
      target: ${BUILD_ENVIRONMENT}
    container_name: nginx-${BUILD_ENVIRONMENT}
    ports:
      - "8080:80"
    depends_on:
      - app
      - pgsql
    networks:
      - api_network
  app:
    build:
      context: .
      dockerfile: .docker/app.Dockerfile
      target: ${BUILD_ENVIRONMENT}
    container_name: app-${BUILD_ENVIRONMENT}
    env_file:
      - .env
    networks:
      - api_network
    depends_on:
      - pgsql
  pgsql:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgsql_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api_network
# Docker Networks
networks:
  api_network:
    driver: bridge
volumes:
  pgsql_volume:
    driver: local
